name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      RELEASE_DIR: /var/www/dcs-docs/prod/releases/${{ github.ref }}/${{ github.run_number }}
      RELEASES_DIR: /var/www/dcs-docs/prod/releases/
      CURRENT_DIR: /var/www/dcs-docs/prod/current
    runs-on:
      - self-hosted
      - dcs

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: CSS
        run: |
          export T=$(date +%s)
          export CSS=css/materal-add-${T}.css
          for L in ru en
          do
            yq -i '.extra_css[0] = strenv(CSS)' $L/mkdocs.yml
            mv $L/docs/css/materal-add.css $L/docs/$CSS
          done

      - name: Build mkdocs
        run: |
          podman run -i --rm -e CI -e COMMITERS_TOKEN=${{secrets.COMMITERS_TOKEN}} -e GOOGLE_ANAL=${{secrets.GOOGLE_ANAL}} -v $PWD:/build -w /build python:3.10-alpine sh -c 'apk add git gcc linux-headers musl-dev && \
          git config --global --add safe.directory /build && \
          cd ru && pip install -r requirements.txt && \
          mkdocs build && \
          cd ../en && mkdocs build && \
          chown -R 1004:1004 ../'

      - name: Deploy
        run: |
          [[ -d ${{env.RELEASE_DIR}}/ru ]] || mkdir -p ${{env.RELEASE_DIR}}/ru
          [[ -d ${{env.RELEASE_DIR}}/en ]] || mkdir -p ${{env.RELEASE_DIR}}/en
          rsync -a ru/site/ ${{env.RELEASE_DIR}}/ru/
          rsync -a en/site/ ${{env.RELEASE_DIR}}/en/

      - name: Switch release
        run: |
          ln -sfn ${{env.RELEASE_DIR}} ${{env.CURRENT_DIR}}
          for R in `ls ${{env.RELEASES_DIR}}/${{ github.ref }} | sort -n | head -n -2`
          do rm -rf ${{env.RELEASES_DIR}}/${{ github.ref }}/$R
          done

